### ISSUE TITLE
What does release bandwidth mean

### ISSUE THREAD

**Issue by BedroomCommunity** [pratyakshm/CleanWin#12]
hi

**Comment by pratyakshm** [comment]
Hello,

**Comment by pratyakshm** [comment]
Hello,
Windows 10 by default reserves around 20% of your total bandwidth for background services like Windows Update, telemetry reporting, third party apps usage, etc.
"Release bandwidth" edits the necessary registry keys required to release that bandwidth, so that 100% of the total bandwidth is fully available to the user. This does **NOT** mean that network access will be blocked to Windows apps & services, it only means that 20% of the total bandwidth would no longer be reserved.

To learn more about this, you may go to Group policy editor using the method below:  
1. Open group policy editor: Win key + R --> input **gpedit.msc** --> Press Enter

**Comment by pratyakshm** [comment]
> hi

Hello,
Windows 10 by default reserves around 20% of your total bandwidth for background services like Windows Update, telemetry, third party apps usage, etc.
"Release bandwidth" edits the necessary registry keys required to release that bandwidth, so that 100% of the total bandwidth is fully available to the user. This does **NOT** mean that network access will be blocked to Windows apps & services, it only means that 20% of the total bandwidth would no longer be reserved.

To learn more follow the method below to go into the specific group policy: 
1. Open group policy editor: Win key + R --> input **gpedit.msc** --> Press Enter.
2. Go to Administrative templates --> Network --> QoS Packet Scheduler.
3. Double tap on **Limit reservable bandwidth**.

Note: The edits made to release the bandwidth is done via the corresponding registry keys, so its status will not be shown in Group policy editor unless the policies are changed using GPE itself. If you choose to reserve bandwidth using the specific group policy, it would override the changes performed by CleanWin - both in GPE (which was by default not changed - Windows behavior) and Registry editor.

**Comment by whyredfire** [comment]
@pratyakshm formal af
